In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [113]:
#get current working directory and go back one level to access the data folder
cwd = os.getcwd()
parent = os.path.dirname(cwd)

In [125]:
train = pd.read_csv(os.path.join(parent, 'train.csv'))
train.index = train['id'].values
train.drop('id', axis=1, inplace=True)

hour0 = "2023-01-01 00:00:00"
hour0 = pd.to_datetime(hour0)
hour0 = hour0
train['delivery_start'] = pd.to_datetime(train['delivery_start'])
train['delivery_end'] = pd.to_datetime(train['delivery_end'])
train['delivery_start'] = (train['delivery_start'] - hour0).dt.total_seconds() / 3600
train['delivery_end'] = (train['delivery_end'] - hour0).dt.total_seconds() / 3600

train['market'] = train['market'].map({'Market A': 0, 'Market B': 1, 'Market C': 2, 'Market D': 3, 'Market E': 4, 'Market F': 5})
clean_train = train.dropna()
train.head()

,target,market,global_horizontal_irradiance,diffuse_horizontal_irradiance,direct_normal_irradiance,cloud_cover_total,cloud_cover_low,cloud_cover_mid,cloud_cover_high,precipitation_amount,...,convective_inhibition,wind_speed_80m,wind_direction_80m,wind_gust_speed_10m,wind_speed_10m,solar_forecast,wind_forecast,load_forecast,delivery_start,delivery_end
0,-1.913,0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,...,0.0,31.253719,245.501450,25.199999,15.077082,0.0,24050.1,38163.01,0.0,1.0
1,-2.210,1,0.0,0.0,0.0,47.0,0.0,0.0,47.0,0.0,...,0.0,40.258881,238.157578,30.239998,14.982228,0.0,24050.1,38163.01,0.0,1.0
2,-2.200,2,0.0,0.0,0.0,21.0,21.0,0.0,0.0,0.0,...,0.0,28.585449,163.162445,24.119999,8.435069,0.0,24050.1,38163.01,0.0,1.0
3,-2.058,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,37.952263,141.934296,33.119999,18.584509,0.0,24050.1,38163.01,0.0,1.0
4,-2.057,4,0.0,0.0,0.0,16.0,0.0,0.0,16.0,0.0,...,0.0,46.244240,234.825195,38.880001,20.746122,0.0,24050.1,38163.01,0.0,1.0

In [124]:
len(np.where(train.isna().any(axis = 1))[0])

2158

In [116]:
train['market']

0         0
1         1
2         2
3         3
4         4
         ..
133621    1
133622    2
133623    5
133625    3
133626    4
Name: market, Length: 132608, dtype: int64

In [117]:
train.describe()

,target,market,global_horizontal_irradiance,diffuse_horizontal_irradiance,direct_normal_irradiance,cloud_cover_total,cloud_cover_low,cloud_cover_mid,cloud_cover_high,precipitation_amount,...,convective_inhibition,wind_speed_80m,wind_direction_80m,wind_gust_speed_10m,wind_speed_10m,solar_forecast,wind_forecast,load_forecast,delivery_start,delivery_end
count,132608.000000,132608.000000,132520.000000,132520.000000,132520.000000,132520.000000,132520.000000,132520.000000,132520.000000,132520.000000,...,130450.000000,132520.000000,132520.000000,132520.000000,132520.000000,132608.000000,132608.000000,132608.000000,132608.000000,132608.000000
mean,33.909258,2.356155,235.322451,60.852413,278.763509,31.079731,20.476720,9.892899,12.905448,0.047428,...,-61.152434,23.785905,159.727056,26.136116,15.752289,5848.465740,13555.019164,53389.008884,12140.624193,12141.624193
std,139.295123,1.644446,319.233798,87.400411,363.014822,40.698349,35.350472,27.309542,29.739493,0.939987,...,119.542970,11.097952,85.717446,12.922435,7.979638,7568.166168,7242.302875,11430.165329,6641.207627,6641.207627
min,-251.794000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1370.000000,0.000000,0.397877,0.360000,0.000000,0.000000,311.300000,30145.720300,0.000000,1.000000
25%,11.739750,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-70.000000,15.484185,113.334068,16.559999,9.693296,0.000000,7492.000000,44945.527700,6631.000000,6632.000000
50%,20.548500,2.000000,10.250000,6.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,23.411074,151.448700,24.480000,14.777550,441.300000,12914.000000,50471.810200,12324.000000,12325.000000
75%,30.033250,4.000000,467.750000,100.500000,656.565811,70.000000,22.000000,0.000000,1.000000,0.000000,...,0.000000,31.322069,194.036270,33.839996,20.858265,11271.100000,19153.800000,60084.359600,17849.000000,17850.000000
max,6252.067000,5.000000,1107.500000,788.000000,1055.374878,100.000000,100.000000,100.000000,100.000000,87.800003,...,5.000000,110.946014,360.000000,114.479996,69.881737,29380.400000,33870.400000,86761.461000,23375.000000,23376.000000

In [118]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 132608 entries, 0 to 133626
Data columns (total 30 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   target                                 132608 non-null  float64
 1   market                                 132608 non-null  int64
 2   global_horizontal_irradiance           132520 non-null  float64
 3   diffuse_horizontal_irradiance          132520 non-null  float64
 4   direct_normal_irradiance               132520 non-null  float64
 5   cloud_cover_total                      132520 non-null  float64
 6   cloud_cover_low                        132520 non-null  float64
 7   cloud_cover_mid                        132520 non-null  float64
 8   cloud_cover_high                       132520 non-null  float64
 9   precipitation_amount                   132520 non-null  float64
 10  visibility                             132520 non-null  float64
 11  air_temperature_2m                     132520 non-null  float64
 12  apparent_temperature_2m                132520 non-null  float64
 13  dew_point_temperature_2m               132520 non-null  float64
 14  wet_bulb_temperature_2m                132520 non-null  float64
 15  surface_pressure                       132520 non-null  float64
 16  freezing_level_height                  132520 non-null  float64
 17  relative_humidity_2m                   132520 non-null  float64
 18  convective_available_potential_energy  132520 non-null  float64
 19  lifted_index                           132520 non-null  float64
 20  convective_inhibition                  130450 non-null  float64
 21  wind_speed_80m                         132520 non-null  float64
 22  wind_direction_80m                     132520 non-null  float64
 23  wind_gust_speed_10m                    132520 non-null  float64
 24  wind_speed_10m                         132520 non-null  float64
 25  solar_forecast                         132608 non-null  float64
 26  wind_forecast                          132608 non-null  float64
 27  load_forecast                          132608 non-null  float64
 28  delivery_start                         132608 non-null  float64
 29  delivery_end                           132608 non-null  float64
dtypes: float64(29), int64(1)
memory usage: 31.4 MB